### ISSUE TITLE
Auto reload on css update

### ISSUE THREAD

**Issue by clarkcx** [PhpGt/Build#39]
Save the SCSS file, CSS compiled, browser reloads! Nice. (Or... it would be.)

**Comment by g105b** [comment]
Might be worth exploring in a separate repository. I'll wait for stable release this week before looking into this more, but it's certainly a nice-to-have.

**Comment by g105b** [comment]
This is possible using a browser extension, and should not be the responsibility of the build process to manage. I will follow up this issue with some suggested extensions when I've tested them.

**Comment by g105b** [comment]
I couldn't find an extension that didn't flake, so I built this to experiment with Firefox extensions: https://github.com/g105b/live-dev

I would like to progress it to have live reloading HTML in the future... but I've spent long enough on this tonight.

Available here once reviewed by Mozilla: https://addons.mozilla.org/en-US/firefox/addon/live-dev/
